# Generated by Django 4.1.7 on 2023-10-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_files_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='unit',
            field=models.CharField(max_length=3),
        ),
    ]
