# Generated by Django 4.1.7 on 2023-10-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_files_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseCode', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=100)),
                ('Fileupload', models.FileField(default=None, max_length=250, null=True, upload_to='media/')),
            ],
        ),
    ]
