# Generated by Django 4.1.7 on 2023-10-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_syllabus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='CourseCode',
            new_name='courseCode',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='Fileupload',
            new_name='fileupload',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='Title',
            new_name='title',
        ),
    ]
