# Generated by Django 4.2.6 on 2023-11-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_email_verification_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_email_verification',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
