# Generated by Django 4.2.6 on 2023-11-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_email_verification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='email',
        ),
    ]
