# Generated by Django 4.2.6 on 2023-11-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_report_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
