# Generated by Django 4.2.6 on 2023-12-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_user_email_verification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_email_verification',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_email_verification',
            name='auth_token',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
