# Generated by Django 4.2.5 on 2023-12-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_user_email_verification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
