# Generated by Django 4.2.5 on 2023-12-15 16:10

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='cafiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=20)),
                ('teachername', models.CharField(max_length=100)),
                ('canumber', models.IntegerField()),
                ('cadate', models.DateTimeField()),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/ca/')),
            ],
        ),
    ]
