# Generated by Django 4.2.6 on 2023-12-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_file_cafiles_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafiles',
            old_name='files',
            new_name='files_ca',
        ),
    ]
