# Generated by Django 4.2.6 on 2023-12-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_cafiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafiles',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
