# Generated by Django 4.2.6 on 2023-12-16 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0026_cafiles_is_verified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cafiles',
            unique_together={('user', 'courseCode', 'canumber', 'cadate')},
        ),
    ]
