# Generated by Django 4.2.6 on 2023-12-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_cafiles_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafiles',
            name='cadate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
