# Generated by Django 4.2.6 on 2023-12-16 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0028_alter_cafiles_cadate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cafiles',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cafiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
