# Generated by Django 4.2.6 on 2023-12-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_cafiles_unique_together_alter_cafiles_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafiles',
            old_name='is_verified',
            new_name='isverified',
        ),
    ]
