# Generated by Django 4.2.5 on 2023-12-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_cafiles_cadate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafiles',
            old_name='files_ca',
            new_name='fileupload',
        ),
    ]
