# Generated by Django 4.2.5 on 2024-01-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rename_files_ca_cafiles_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/profile_photos/'),
        ),
    ]
