# Generated by Django 4.2.5 on 2024-01-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(default='not uploaded', max_length=250, null=True, upload_to='media/profile_photos/'),
        ),
    ]
