# Generated by Django 4.2.5 on 2024-01-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/profile_photos/'),
        ),
    ]
