# Generated by Django 4.2.6 on 2024-02-08 07:41

import cloudinary_storage.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0036_alter_profile_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('Description', models.CharField(blank=True, max_length=8000)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Images', models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='media/discussions/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Syllabus',
        ),
    ]
